[default]
cli_colors = true
port = 8000
# Generate secret_key with `openssl rand -base64 64`
secret_key = <insert_secret_key>

[default.oauth.github]
provider = "GitHub"
client_id = <insert_client_id>
# DO NOT COMMIT OR PUBLISH THIS SECRET
client_secret = <insert_client_secret>
redirect_uri = "http://localhost:8000/auth/github"
